In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("students.csv")
df["marks"]=pd.to_numeric(df["marks"],errors="coerce")
df=df.dropna(subset=["marks","age"])
df

      name   age  marks
0   Arjabi  20.0   88.0
1   Preyas  20.0   82.0
3  Abhipsa  20.0   80.0
5   Anusha  21.0   74.0

In [34]:
df=df[df["marks"]>80]
df

     name   age  marks
0  Arjabi  20.0   88.0
1  Preyas  20.0   82.0

In [35]:
df=df[df["age"]>2]
df

     name   age  marks
0  Arjabi  20.0   88.0
1  Preyas  20.0   82.0

In [48]:
df=df[(df["marks"]>70) & (df["age"]>20)]
df

     name   age  marks
5  Anusha  21.0   74.0

In [62]:
df=df.sort_values("marks")
df

      name   age  marks
5   Anusha  21.0   74.0
3  Abhipsa  20.0   80.0
1   Preyas  20.0   82.0
0   Arjabi  20.0   88.0

the above gives the values in ascending order. For descending order, add ascending=False.

In [64]:
df=df.sort_values("marks",ascending=False)
df

      name   age  marks
0   Arjabi  20.0   88.0
1   Preyas  20.0   82.0
3  Abhipsa  20.0   80.0
5   Anusha  21.0   74.0

Add new column using vectorization.

In [5]:
df["bonus marks"]=df["marks"]+5
df

      name   age  marks  bonus marks
0   Arjabi  20.0   88.0         93.0
1   Preyas  20.0   82.0         87.0
3  Abhipsa  20.0   80.0         85.0
5   Anusha  21.0   74.0         79.0

Basic aggregation

In [69]:
print(f"Mean= {df["marks"].mean()}")
print(f"Max= {df["marks"].max()}")
print(f"Min= {df["marks"].min()}")

Mean= 81.0
Max= 88.0
Min= 74.0

Adding new column GRADE using vectorization (pd.cut())

In [6]:
df["grade"]=pd.cut(
    df["marks"],
    bins=[0,60,80,100],
    labels=['C','B','A'],
    right=False
)
df

      name   age  marks  bonus marks grade
0   Arjabi  20.0   88.0         93.0     A
1   Preyas  20.0   82.0         87.0     A
3  Abhipsa  20.0   80.0         85.0     A
5   Anusha  21.0   74.0         79.0     B

Adding new column pass or fail using vectorization

In [7]:
df["Result"]=pd.cut(
    df["marks"],
    bins=[0,80,100],
    labels=["Fail","Pass"],
    right=False
)
df

      name   age  marks  bonus marks grade Result
0   Arjabi  20.0   88.0         93.0     A   Pass
1   Preyas  20.0   82.0         87.0     A   Pass
3  Abhipsa  20.0   80.0         85.0     A   Pass
5   Anusha  21.0   74.0         79.0     B   Fail

Analysis

Which grade has highest average marks

In [12]:
grade_wise_avg=df.groupby("grade")["marks"].mean()
print(grade_wise_avg)
print(grade_wise_avg.idxmax())

grade
B    74.000000
A    83.333333
Name: marks, dtype: float64
A

How many students are in each grade

In [27]:
count_by_grade=df["grade"].value_counts()
count_by_grade

grade
A    3
B    1
C    0
Name: count, dtype: int64

Who has the highest marks?

In [21]:
top=df.loc[df["marks"].idxmax()]
top

name           Arjabi
age              20.0
marks            88.0
bonus marks      93.0
grade               A
Result           Pass
Name: 0, dtype: object

Students scoring above average marks

In [25]:
overall_mean=df["marks"].mean()
print(overall_mean)
print(df[df["marks"]>overall_mean])

81.0
     name   age  marks  bonus marks grade Result
0  Arjabi  20.0   88.0         93.0     A   Pass
1  Preyas  20.0   82.0         87.0     A   Pass

In [31]:
df["marks"].value_counts()
print(df["marks"].idxmin())

5