In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("sales.csv")
df["price"]=pd.to_numeric(df["price"],errors="coerce")
df["quantity"]=pd.to_numeric(df["quantity"],errors="coerce")
df=df.dropna(subset=["price","quantity"])
df["amount"]=df["price"]*df["quantity"]
df.head()

        product      category    price  quantity     amount
1        Bottle   Accessories    150.0       2.0      300.0
3        Marker    Stationery     30.0       4.0      120.0
4        Laptop   Electronics  85000.0      12.0  1020000.0
5    Smartphone   Electronics  42000.0      25.0  1050000.0
6  Office Chair     Furniture   9500.0      10.0    95000.0

Task 1: Details of products where price>100

In [3]:
filtered_df=df[df["price"]>100]
filtered_df["product"]

1           Bottle
4           Laptop
5       Smartphone
6     Office Chair
8         Backpack
9       Headphones
10       Desk Lamp
11      Coffee Mug
Name: product, dtype: str

Task 2: To show rows where quantity>=5

In [4]:
filtered=df[df["quantity"]>=5]
filtered

         product      category    price  quantity     amount
4         Laptop   Electronics  85000.0      12.0  1020000.0
5     Smartphone   Electronics  42000.0      25.0  1050000.0
6   Office Chair     Furniture   9500.0      10.0    95000.0
7            Pen    Stationery     25.0     500.0    12500.0
8       Backpack          Bags   1800.0      40.0    72000.0
9     Headphones   Electronics   3200.0      30.0    96000.0
10     Desk Lamp   Electronics   1500.0      18.0    27000.0
11    Coffee Mug   Kitchenware    450.0      60.0    27000.0

Task 3: To show rows where price>1000 and quantity>2

In [5]:
filtered1=df[(df["price"]>1000)&(df["quantity"]>2)]
filtered1

         product      category    price  quantity     amount
4         Laptop   Electronics  85000.0      12.0  1020000.0
5     Smartphone   Electronics  42000.0      25.0  1050000.0
6   Office Chair     Furniture   9500.0      10.0    95000.0
8       Backpack          Bags   1800.0      40.0    72000.0
9     Headphones   Electronics   3200.0      30.0    96000.0
10     Desk Lamp   Electronics   1500.0      18.0    27000.0

Sorting dataset by amount (highest first)

In [6]:
sorted_df=df.sort_values(by="amount",ascending=False)
sorted_df

         product      category    price  quantity     amount
5     Smartphone   Electronics  42000.0      25.0  1050000.0
4         Laptop   Electronics  85000.0      12.0  1020000.0
9     Headphones   Electronics   3200.0      30.0    96000.0
6   Office Chair     Furniture   9500.0      10.0    95000.0
8       Backpack          Bags   1800.0      40.0    72000.0
10     Desk Lamp   Electronics   1500.0      18.0    27000.0
11    Coffee Mug   Kitchenware    450.0      60.0    27000.0
7            Pen    Stationery     25.0     500.0    12500.0
1         Bottle   Accessories    150.0       2.0      300.0
3         Marker    Stationery     30.0       4.0      120.0

Create column: Price label

In [7]:
def price_label(price):
    if price>5000:
        return "High"
    elif price>2000 and price<=5000:
        return "Medium"
    else:
        return "Low"
df["Price Label"]=df["price"].apply(price_label)
df

         product      category    price  quantity     amount Price Label
1         Bottle   Accessories    150.0       2.0      300.0         Low
3         Marker    Stationery     30.0       4.0      120.0         Low
4         Laptop   Electronics  85000.0      12.0  1020000.0        High
5     Smartphone   Electronics  42000.0      25.0  1050000.0        High
6   Office Chair     Furniture   9500.0      10.0    95000.0        High
7            Pen    Stationery     25.0     500.0    12500.0         Low
8       Backpack          Bags   1800.0      40.0    72000.0         Low
9     Headphones   Electronics   3200.0      30.0    96000.0      Medium
10     Desk Lamp   Electronics   1500.0      18.0    27000.0         Low
11    Coffee Mug   Kitchenware    450.0      60.0    27000.0         Low

Dataset Exploration

Number of products per category

In [8]:
numpercat=df["category"].value_counts()
numpercat

category
 Electronics    4
Accessories     1
Stationery      1
 Furniture      1
 Stationery     1
 Bags           1
 Kitchenware    1
Name: count, dtype: int64

Unique Categories

In [9]:
unique_cat=df["category"].unique()
unique_cat

<StringArray>
[ 'Accessories',   'Stationery', ' Electronics',   ' Furniture',
  ' Stationery',        ' Bags', ' Kitchenware']
Length: 7, dtype: str

In [10]:
print(f"Total categories is {df["category"].nunique()}")

Total categories is 7

Mini Analysis

1. Which product generated the highest amount?

In [37]:
highest_amt=df["amount"].max()
high_amt_prod=df[df["amount"]==highest_amt]
print(high_amt_prod)
high_amt_prod

<pandas.core.indexing._LocIndexer object at 0x0000025CF33B6B70>

      product      category    price  quantity     amount Price Label
5  Smartphone   Electronics  42000.0      25.0  1050000.0        High

In [41]:
high_amt_prod=df.loc[df["amount"].idxmax(),["product","category"]]
print(f"{high_amt_prod} generated the highest amount")

product       Smartphone
category     Electronics
Name: 5, dtype: str generated the highest amount

2. Which category has most products?

In [27]:
cat_wise=df.groupby("category")["product"].nunique()
print(f"{cat_wise.idxmax()} category has most products")

 Electronics category has most products

3. Average price per category

In [30]:
avg_price_cat=df.groupby("category",as_index=False)["price"].mean()
avg_price_cat=avg_price_cat.rename(columns={"price":"avg price"})
avg_price_cat

       category  avg price
0          Bags     1800.0
1   Electronics    32925.0
2     Furniture     9500.0
3   Kitchenware      450.0
4    Stationery       25.0
5   Accessories      150.0
6    Stationery       30.0